exec-once = uwsm-app -- mako
# Wallpaper is managed by Noctalia (no swaybg needed)
exec-once = uwsm-app -- swayosd-server
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Slow app launch fix -- set systemd vars
exec-once = systemctl --user import-environment $(env | cut -d'=' -f1)
exec-once = dbus-update-activation-environment --systemd --all

exec-once = noctalia
