bind = SUPER, C, sendshortcut, CTRL, Insert
bind = SUPER, V, sendshortcut, SHIFT, Insert
bind = SUPER, X, sendshortcut, CTRL, X
bind = SUPER CTRL, V, exec, walker -m clipboard --width 644 --maxheight 300 --minheight 300
