# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Environment variables
source = ~/.config/hypr/envs.conf

# Display configuration
source = ~/.config/hypr/monitors.conf

# Input devices
source = ~/.config/hypr/input.conf

# Keybindings
source = ~/.config/hypr/media.conf
source = ~/.config/hypr/clipboard.conf
source = ~/.config/hypr/tiling.conf
source = ~/.config/hypr/utilities.conf

# Look and feel
source = ~/.config/hypr/looknfeel.conf

# Window rules
source = ~/.config/hypr/windows.conf

# User application bindings (overrides)
source = ~/.config/hypr/bindings.conf

# Autostart
source = ~/.config/hypr/autostart.conf

# Theme overrides (managed by omarchy-theme-set)
source = ~/.config/omarchy/current/theme/hyprland.conf

$activeBorderColor = rgba(c6d0f5ba)

general {
    col.active_border = $activeBorderColor
}

group {
    col.border_active = $activeBorderColor
}

windowrule = min_size 1920 1080, match:class ^(org\.omarchy\.btop)$
