# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    gaps_in = 2
    gaps_out = 3
    border_size = 2

    # Use master layout instead of dwindle
   # layout = master
}

misc {
    enable_anr_dialog = false
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 8
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

windowrule = opacity 1.0 1.0, match:class .*

windowrule {
    name = min_size_for_floating
    match:float = 1
    match:class =.*[Bb]lender.*
    min_size = 800 600
}

windowrule {
    name = steam-friends-list
    match:class = steam
    match:title = Friends List
    min_size = 300 300
    max_size = 300 600
    size = 300 600
}

#windowrule = float, move 2818 848, size 1023 747, class:dwarf_world
windowrule = float on, match:class dwarf_world

windowrule = opacity 1.0 1.0, match:class dev.zed.Zed
