# Menus
bind = SUPER, SPACE, exec, pkill -x rofi || rofi -show drun
bind = SUPER ALT, SPACE, exec, omarchy-menu
bind = SUPER CTRL, E, exec, qs ipc -c noctalia-shell call launcher emoji
bind = SUPER, ESCAPE, exec, ~/.config/hypr/scripts/power-menu.sh
bindl = , XF86PowerOff, exec, ~/.config/hypr/scripts/power-menu.sh
bind = SUPER, K, exec, hyprctl binds
bind = , XF86Calculator, exec, gnome-calculator

# Aesthetics
bind = SUPER SHIFT, SPACE, exec, ~/.config/hypr/scripts/toggle-waybar.sh
bind = SUPER SHIFT CTRL, SPACE, exec, ~/.config/hypr/scripts/theme-menu.sh
bind = SUPER, BACKSPACE, exec, hyprctl dispatch setprop "address:$(hyprctl activewindow -j | jq -r '.address')" opaque toggle
bind = SUPER SHIFT, BACKSPACE, exec, ~/.config/hypr/scripts/toggle-gaps.sh

# Notifications
bind = SUPER, COMMA, exec, makoctl dismiss
bind = SUPER SHIFT, COMMA, exec, makoctl dismiss --all
bind = SUPER CTRL, COMMA, exec, makoctl mode -t do-not-disturb && makoctl mode | grep -q 'do-not-disturb' && notify-send "Silenced notifications" || notify-send "Enabled notifications"
bind = SUPER ALT, COMMA, exec, makoctl invoke
bind = SUPER SHIFT ALT, COMMA, exec, makoctl restore

# Toggle idling
bind = SUPER CTRL, I, exec, ~/.config/hypr/scripts/toggle-idle.sh

# Captures
bind = , PRINT, exec, grim -g "$(slurp)" - | satty --filename -
bind = SHIFT, PRINT, exec, grim -g "$(slurp)" - | wl-copy
bind = ALT, PRINT, exec, wf-recorder -a -f "$(xdg-user-dir VIDEOS)/recording-$(date +%Y%m%d-%H%M%S).mp4" & notify-send "Screen Recording" "Started"
bind = SUPER, PRINT, exec, pkill hyprpicker || hyprpicker -a

# File sharing
bind = SUPER CTRL, S, exec, rofi -dmenu -i -p "Share" -theme-str "window { width: 380px; } listview { lines: 6; }"

# Information
bind = SUPER CTRL ALT, T, exec, notify-send " $(date +"%A %H:%M  —  %d %B W%V %Y")"
bind = SUPER CTRL ALT, B, exec, notify-send " Battery at $(cat /sys/class/power_supply/BAT*/capacity 2>/dev/null || echo 'N/A')%"

# Control panels
bind = SUPER CTRL, A, exec, uwsm-app -- ghostty -e wiremix
bind = SUPER CTRL, B, exec, bash -c 'rfkill unblock bluetooth; uwsm-app -- ghostty -e bluetui'
bind = SUPER CTRL, W, exec, bash -c 'rfkill unblock wifi; uwsm-app -- ghostty -e impala'
bind = SUPER CTRL, T, exec, uwsm-app -- ghostty -e btop
