/*
 * Rofi color palette — generated by omarchy-theme-set-templates from the
 * current theme's colors.toml. Do not edit the generated file in
 * ~/.config/omarchy/current/theme/rofi.rasi; edit this template instead.
 */

* {
    bg:           {{ background }};
    bg-alt:       {{ color0 }};       /* subtle surface — like mocha surface0 */
    fg:           {{ foreground }};
    fg-alt:       {{ color7 }};
    accent:       {{ accent }};
    border-col:   {{ accent }};
    /* Selection uses an elevated dark surface (color8 = bright black, like
       mocha surface1/surface2) with light text. Always readable regardless
       of which omarchy theme defines `selection_*` as accent-on-light. */
    sel-bg:       {{ color8 }};
    sel-fg:       {{ foreground }};
    cursor-col:   {{ cursor }};
    muted:        {{ color8 }};
    urgent:       {{ color1 }};
    active:       {{ color2 }};
}
